= Cheatsheets

[[ActionNodeConfig]]
== ActionNodeConfig

++++
 Action node configuration model. It is model for  JSON object.

 <pre>
 node {
   factory = action
   config { //represented by ActionNodeConfig
     ...
   }
 }
 </pre>
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[action]]`@action`|`String`|+++
Sets  name. The specified Action is executed
 during processing of given graph node.
+++
|===

[[ActionNodeFactoryConfig]]
== ActionNodeFactoryConfig

++++
 Action Node factory config model.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[actions]]`@actions`|`link:dataobjects.html#ActionFactoryOptions[ActionFactoryOptions]`|+++
The dictionary maps action name to action factory options.
+++
|===

[[DefaultTaskFactoryConfig]]
== DefaultTaskFactoryConfig

++++
 Default Task Factory config model.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[logLevel]]`@logLevel`|`String`|+++
The global node log level.
+++
|[[nodeFactories]]`@nodeFactories`|`Array of link:dataobjects.html#NodeFactoryOptions[NodeFactoryOptions]`|+++
The array/list of graph node factory options defines node factories taking part in the creation
 of graph.
+++
|[[taskNameKey]]`@taskNameKey`|`String`|+++
The fragment's configuration key specifies a task assigned to a fragment by the task name.
+++
|[[tasks]]`@tasks`|`link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
The dictionary that maps a task name to a directed acyclic graph (DAG) of nodes.
+++
|===

[[GraphNodeOptions]]
== GraphNodeOptions

++++
 Graph node options model.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[action]]`@action`|`String`|+++
Sets a node factory name to <code>ActionNodeFactory.NAME</code> and configures the action.
+++
|[[actions]]`@actions`|`Array of link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
Sets a node factory name to <code>SubtasksNodeFactory.NAME</code> and configures subgraphs.
+++
|[[node]]`@node`|`link:dataobjects.html#NodeOptions[NodeOptions]`|+++
Node options define a node factory and its configuration.
+++
|[[on]]`@on`|`link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
Alias for "onTransitions".
 See link
+++
|[[onTransitions]]`@onTransitions`|`link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
The outgoing graph node edges, called transitions. A transition is named graph edge that
 defines the next graph node in fragment's processing.
+++
|[[subtasks]]`@subtasks`|`Array of link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
Sets a node factory name to <code>SubtasksNodeFactory.NAME</code> and configures subgraphs.
+++
|===

[[LogLevelConfig]]
== LogLevelConfig


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[logLevel]]`@logLevel`|`String`|-
|===

[[NodeFactoryOptions]]
== NodeFactoryOptions

++++
 Node Factory options model.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
The JSON object that contains node factory configuration entries.
+++
|[[factory]]`@factory`|`String`|+++
The node factory name that identifies <code>NodeFactory</code> implementation.
+++
|===

[[NodeOptions]]
== NodeOptions

++++
 Node options defines factory that should be used to create node and its configuration.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Sets node configuration. It does not parse JSON, the configuration is passed to node factory.
+++
|[[factory]]`@factory`|`String`|+++
Sets node factory name
+++
|===

[[SubtasksNodeConfig]]
== SubtasksNodeConfig

++++
 Subtask Node configuration.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[subtasks]]`@subtasks`|`Array of link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
The array/list of subgraphs/subtasks that can be executed in parallel.
+++
|===

