= Cheatsheets

[[Fragment]]
== Fragment

++++
 Represents a small piece of a request that may be processed independently.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[body]]`@body`|`String`|+++
Contains the body of a Fragment that is the final result of the fragment processing. Body can
 be updated and transformed many times during processing.
+++
|[[configuration]]`@configuration`|`Json object`|+++
Configuration containing all information necessary to process Fragment. Configuration is
 immutable and can be set only once.
+++
|[[id]]`@id`|`String`|+++
Unique identifier of the Fragment. Its representaion is currently a <code>String</code>
 representation of <code>UUID</code>. It can never change during processing.
+++
|[[payload]]`@payload`|`Json object`|+++
Any additional data that is associated with the Fragment. Payload can be appended (and
 replaced) during processing but never cleared.
+++
|[[type]]`@type`|`String`|+++
Type of a Fragment. Different types of Fragments can be processed in separate ways. Example
 type could be <code>snippet</code>. It can never change during processing.
+++
|===

[[FragmentContext]]
== FragmentContext


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[clientRequest]]`@clientRequest`|`link:dataobjects.html#ClientRequest[ClientRequest]`|-
|[[fragment]]`@fragment`|`link:dataobjects.html#Fragment[Fragment]`|-
|===

[[FragmentResult]]
== FragmentResult

++++
 Result of the link.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[fragment]]`@fragment`|`link:dataobjects.html#Fragment[Fragment]`|+++
A <code>Fragment</code> transformed or updated during applying the link.
+++
|[[log]]`@log`|`Json object`|+++
Log data produced by link. It is a JSON-based value specific to the
 operation.
+++
|[[transition]]`@transition`|`String`|+++
A text value state of link that determines next steps in business logic.
+++
|===

