= Cheatsheets

[[ActionFactoryOptions]]
== ActionFactoryOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Sets <code>Action</code> configuration that is passed to Action.
+++
|[[doAction]]`@doAction`|`String`|+++
Sets the name of the base <code>Action</code> that will be triggered while creating current <code>Action</code>. In not set (<code>null</code>), given action will have no base actions.
+++
|[[factory]]`@factory`|`String`|+++
Sets <code>Action</code> factory name.
+++
|===

[[ActionNodeConfig]]
== ActionNodeConfig

++++
 Action node configuration model. It is model for  JSON object.

 <pre>
 node {
   factory = action
   config { //represented by ActionNodeConfig
     ...
   }
 }
 </pre>
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[action]]`@action`|`String`|+++
Sets link name. The specified Action is executed
 during processing of given graph node.
+++
|===

[[ActionNodeFactoryConfig]]
== ActionNodeFactoryConfig


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[actions]]`@actions`|`link:dataobjects.html#ActionFactoryOptions[ActionFactoryOptions]`|-
|===

[[DefaultTaskFactoryConfig]]
== DefaultTaskFactoryConfig

++++
 Default Task Factory config model.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[logLevel]]`@logLevel`|`String`|+++
The global node log level.
+++
|[[nodeFactories]]`@nodeFactories`|`Array of link:dataobjects.html#NodeFactoryOptions[NodeFactoryOptions]`|+++
The array/list of graph node factory options defines node factories taking part in the creation
 of graph.
+++
|[[taskNameKey]]`@taskNameKey`|`String`|+++
The fragment's configuration key specifies a task assigned to a fragment by the task name.
+++
|[[tasks]]`@tasks`|`link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
The dictionary that maps a task name to a directed acyclic graph (DAG) of nodes.
+++
|===

[[FragmentsHandlerOptions]]
== FragmentsHandlerOptions

++++
 Fragments Handler options model.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[taskFactories]]`@taskFactories`|`Array of link:dataobjects.html#TaskFactoryOptions[TaskFactoryOptions]`|+++
The array/list of task factory options defines factories taking part in the creation of tasks. First
 items on the list have the highest priority.
+++
|===

[[GraphNodeOptions]]
== GraphNodeOptions

++++
 It is link processing configuration. Task is graph of nodes (in
 fact it is tree structure). It defines  and outgoing directed graph edges,
 called <code>Transitions</code>.

 It represents JSON configuration:
 <pre>
 {
   node = {
     factory = action
     config {
       action = a
     }
   }
   onTransitions {
     _success {
       node = {
         factory = action
         config {
           action = b
         }
       }
     }
   }
 }
 </pre>

 Please note that Transitions define next graph nodes.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[action]]`@action`|`String`|+++

+++
|[[actions]]`@actions`|`Array of link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++

+++
|[[node]]`@node`|`link:dataobjects.html#NodeOptions[NodeOptions]`|+++
Sets node options defining node factory and its configuration.
+++
|[[onTransitions]]`@onTransitions`|`link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
Sets outgoing graph node edges, called <code>Transitions</code>. Transition is String, <code>onTransitions</code> map links Transition with next graph node.
+++
|[[subtasks]]`@subtasks`|`Array of link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++

+++
|===

[[LogLevelConfig]]
== LogLevelConfig


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[logLevel]]`@logLevel`|`String`|-
|===

[[NodeFactoryOptions]]
== NodeFactoryOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|-
|[[factory]]`@factory`|`String`|-
|===

[[NodeOptions]]
== NodeOptions

++++
 Node options defines factory that should be used to create node and its configuration.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Sets node configuration. It does not parse JSON, the configuration is passed to node factory.
+++
|[[factory]]`@factory`|`String`|+++
Sets node factory name
+++
|===

[[SubtasksNodeConfig]]
== SubtasksNodeConfig

++++
 Subtask node configuration. It is model for  JSON object.

 <pre>
 node {
   factory = subtasks
   config { //represented by SubtasksNodeConfigOptions
     ...
   }
 }
 </pre>
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[subtasks]]`@subtasks`|`Array of link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
Sets list of  that represents link
 that will be executed in parallel.
+++
|===

[[TaskFactoryOptions]]
== TaskFactoryOptions

++++
 Task Factory options model. It specifies task factory by its name and provides task factory
 config.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
The JSON object that contains task factory configuration entries.
+++
|[[factory]]`@factory`|`String`|+++
The task factory name that identifies <code>TaskFactory</code> implementation.
+++
|===

