= Cheatsheets

[[ActionNodeConfigOptions]]
== ActionNodeConfigOptions

++++
 Action node configuration model. It is model for link JSON object.

 <pre>
 node {
   factory = action
   config {
     HERE
   }
 }
 </pre>
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[action]]`@action`|`String`|+++
Sets link name. The specified Action is executed
 during processing of given graph node.
+++
|===

[[ActionOptions]]
== ActionOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Sets <code>Action</code> configuration that is passed to Action.
+++
|[[doAction]]`@doAction`|`String`|+++
Sets the name of the base <code>Action</code> that will be triggered while creating current <code>Action</code>. In not set (<code>null</code>), given action will have no base actions.
+++
|[[factory]]`@factory`|`String`|+++
Sets <code>Action</code> factory name.
+++
|===

[[FragmentsHandlerOptions]]
== FragmentsHandlerOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[actions]]`@actions`|`link:dataobjects.html#ActionOptions[ActionOptions]`|+++
Sets named actions with their factory configuration.
+++
|[[taskKey]]`@taskKey`|`String`|-
|[[tasks]]`@tasks`|`link:dataobjects.html#TaskOptions[TaskOptions]`|+++
Sets <code>Task</code> list, which are named, directed graphs of <code>Actions</code>.
+++
|===

[[GraphNodeOptions]]
== GraphNodeOptions

++++
 It is link processing configuration. Task is graph of nodes (in
 fact it is tree structure). It defines link and outgoing directed graph edges,
 called <code>Transitions</code>.

 It represents JSON configuration:
 <pre>
 {
   node = {
     factory = action
     config {
       action = a
     }
   }
   onTransitions {
     _success {
       node = {
         factory = action
         config {
           action = b
         }
       }
     }
   }
 }
 </pre>

 Please note that Transitions define next graph nodes.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[action]]`@action`|`String`|+++

+++
|[[actions]]`@actions`|`Array of link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++

+++
|[[composite]]`@composite`|`Boolean`|-
|[[node]]`@node`|`link:dataobjects.html#NodeOptions[NodeOptions]`|+++
Sets node options defining node factory and its configuration.
+++
|[[onTransitions]]`@onTransitions`|`link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
Sets outgoing graph node edges, called <code>Transitions</code>. Transition is String, <code>onTransitions</code> map links Transition with next graph node.
+++
|[[subTasks]]`@subTasks`|`Array of link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++

+++
|[[subtasks]]`@subtasks`|`Array of link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++

+++
|===

[[NodeOptions]]
== NodeOptions

++++
 Node options defines factory that should be used to create node and its configuration.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Sets node configuration. It does not parse JSON, the configuration is passed to node factory.
+++
|[[factory]]`@factory`|`String`|+++
Sets node factory name
+++
|===

[[SubTasksNodeConfigOptions]]
== SubTasksNodeConfigOptions

++++
 Subtask node configuration.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[subTasks]]`@subTasks`|`Array of link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
Sets list of link that represents link that
 will be executed in parallel.
+++
|[[subtasks]]`@subtasks`|`Array of link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|-
|===

[[TaskOptions]]
== TaskOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|-
|[[factory]]`@factory`|`String`|-
|[[graph]]`@graph`|`link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|-
|===

