= Cheatsheets

[[ActionOptions]]
== ActionOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Sets <code>Action</code> configuration that is passed to Action.
+++
|[[doAction]]`@doAction`|`String`|+++
Sets the name of the base <code>Action</code> that will be triggered while creating current <code>Action</code>. In not set (<code>null</code>), given action will have no base actions.
+++
|[[factory]]`@factory`|`String`|+++
Sets <code>Action</code> factory name.
+++
|===

[[FragmentsHandlerOptions]]
== FragmentsHandlerOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[actions]]`@actions`|`link:dataobjects.html#ActionOptions[ActionOptions]`|+++
Sets named actions with their factory configuration.
+++
|[[taskKey]]`@taskKey`|`String`|-
|[[tasks]]`@tasks`|`link:dataobjects.html#TaskOptions[TaskOptions]`|+++
Sets <code>Task</code> list, which are named, directed graphs of <code>Actions</code>.
+++
|===

[[NodeOptions]]
== NodeOptions

++++
 Defines graph's verticle with outgoing directed edges (<code>Transitions</code>).
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[action]]`@action`|`String`|+++
Sets <code>Action</code> name. This action will be executed during processing given graph node. If
 <code>action</code> field is defined, Node configured by it will be treated as Action Node.
+++
|[[actions]]`@actions`|`Array of link:dataobjects.html#NodeOptions[NodeOptions]`|+++
Sets list of <code>NodeOptions</code> that represents <code>Actions</code> that will be executed in
 parallel. If this array is defined and <code>action</code> field is left empty, Node will be treated
 as Composite.
+++
|[[composite]]`@composite`|`Boolean`|-
|[[onTransitions]]`@onTransitions`|`link:dataobjects.html#NodeOptions[NodeOptions]`|+++
Sets the <code>Map</code> of possible onTransitions for the given graph node. If the Node is <code>Composite</code> only <code>_success</code> and <code>_error</code> transitions can be configured.
+++
|===

[[TaskOptions]]
== TaskOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`link:dataobjects.html#NodeOptions[NodeOptions]`|-
|[[factory]]`@factory`|`link:dataobjects.html#TaskProviderOptions[TaskProviderOptions]`|-
|===

[[TaskProviderOptions]]
== TaskProviderOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|-
|[[name]]`@name`|`String`|-
|===

