= Cheatsheets

[[ActionFactoryOptions]]
== ActionFactoryOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[config]]`@config`|`Json object`|+++
Sets <code>Action</code> configuration that is passed to Action Factory.
+++
|[[doAction]]`@doAction`|`String`|+++
Sets the name of the base <code>Action</code> that will be triggered while creating current <code>Action</code>. In not set (<code>null</code>), given action will have no base actions.
+++
|[[factory]]`@factory`|`String`|+++
Sets <code>Action</code> factory name.
+++
|===

[[FragmentsHandlerOptions]]
== FragmentsHandlerOptions


[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[actions]]`@actions`|`link:dataobjects.html#ActionFactoryOptions[ActionFactoryOptions]`|+++
Sets named actions with their factory configuration.
+++
|[[tasks]]`@tasks`|`link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
Sets <code>Task</code> list, which are named, directed graphs of <code>Actions</code>.
+++
|===

[[GraphNodeOptions]]
== GraphNodeOptions

++++
 Defines graph's verticle with outgoing directed edges (<code>Transitions</code>).
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[action]]`@action`|`String`|+++
Sets <code>Action</code> name. This action will be executed during processing given graph node.
+++
|[[onTransitions]]`@onTransitions`|`link:dataobjects.html#GraphNodeOptions[GraphNodeOptions]`|+++
Sets the <code>Map</code> of possible onTransitions for the given graph node.
+++
|===

